name: Build LaTeX document

on: 
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Bump version and tag main
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          default_bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish document as release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Cookbook ${{ steps.tag_version.outputs.new_tag }}
          files: main.pdf 
